name: flutter_truecaller
description: |
  Truecaller SDK plugin for Flutter apps. Verification via this plugin
  enables you to quickly verify / signup / login your users on the basis of their mobile number
version: 0.3.0
homepage: https://github.com/dipinarora9/flutter_truecaller

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dipinarora9.flutter_truecaller
        pluginClass: FlutterTruecallerPlugin